CustomersAndOrdersCC/WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

using CustomersAndOrdersCC.Data;
using CustomersAndOrdersCC.Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

using WebApplication.Models;


namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {        
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Comparison(ModelClass model)
        {

            HttpContext.Session.SetString("FirstName", model.MVCFirstName);
            HttpContext.Session.SetString("LastName", model.MVCLastName);

            var efcservice = new NewEFCService();
            List<Customer> PersInfoOld = new List<Customer>();
            List<Customer> PersInfo = new List<Customer>();
            NewCustomer ItemNewInfo = new NewCustomer();
            List<NewCustomer> NewInfo = new List<NewCustomer>();

            PersInfo = efcservice.SearchPerson(model.MVCFirstName, model.MVCLastName);
            
            //next time persinfo is filled (from old db) append instead of replace( the new)
            
            //change personID to uppercase



            string Baseurl = "http://localhost:5000/";

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);
                //no need
                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient 
                //var
                HttpResponseMessage Res = await client.GetAsync("api/values");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var PersonResponse = await Res.Content.ReadAsStringAsync();

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    PersInfoOld = JsonConvert.DeserializeObject<List<Customer>>(PersonResponse);

                }

                //keep entries in List : with correct combination , delete all other entries 
                PersInfoOld.RemoveAll(x => x.FirstName != model.MVCFirstName || x.LastName != model.MVCLastName);

                //loop through result from new DB and delete the same entries from the result of old DB 
                foreach (var myIndex in PersInfo.Where(n=>n.BusinessEntityID != null )) 
                {
                    PersInfoOld.RemoveAll(x => x.BusinessEntityID == myIndex.BusinessEntityID);
                }

                foreach (var myIndex in PersInfoOld)
                {
                    myIndex.OldDatabase = true;
                    PersInfo.Add(myIndex);
                }

                
                HttpContext.Session.SetObjectAsJson("_Customer", PersInfo);


                if (PersInfo.Any()) //υπάρχει OldCustomer άρα View "CustomerOverview"
                {
                    return View("CustomerOverview", PersInfo);
                }
                else //δεν υπάρχει OldCustomer άρα View "CreateNewCustomer"
                {

                    ItemNewInfo.LastName = model.MVCLastName;
                    ItemNewInfo.FirstName = model.MVCFirstName;


                    //ItemNewInfo.Add(NewCustomer);
                    //NewInfo[1].FirstName = model.MVCFirstName;  //bring field attribute to New List in the next view
                    //NewInfo[1].LastName = model.MVCLastName;    //             >>           >>
                    return View("CreateNewCustomer", ItemNewInfo);
  
                }
               
            }

        }
        public IActionResult CreateNewCustomer(ModelClass model)
        {
            string babis = HttpContext.Session.GetString("FirstName");
            
            return View();
        }

        public IActionResult SelectCustomer(int id)
        {
            Customer ItemNewInfo = new Customer();
            CombinedModel Combo = new CombinedModel();
            var efcservice = new NewEFCService();
            var PersInfo = HttpContext.Session.GetObjectFromJson<List<Customer>>("_Customer");


            ItemNewInfo = PersInfo[PersInfo.FindIndex(a => a.BusinessEntityID == id)];

            //((ItemNewInfo.OldDatabase == true) ? return View("CreateNewCustomer", ItemNewInfo) : return View())


            Combo = efcservice.FetchProducts(ItemNewInfo);
            HttpContext.Session.SetObjectAsJson("_Combo", Combo);
            return (ItemNewInfo.OldDatabase == true) ? View("CreateNewCustomer", ItemNewInfo) : View("Order", Combo );



        }      




        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Landing()
        {
            return View();
        }


        public IActionResult SelectOldCustomer()
        {
            return View();
            
        }

        

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomersAndOrdersCC/WebApplication/Controllers/OcOverviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using CustomersAndOrdersCC.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class OcOverviewController : Controller
    {
        [HttpPost]
        public async Task<ActionResult> CustomerOverview(ModelClass model)
        {
            //I have already defined this globally as static :
            List<OldCustomer> PersInfo = new List<OldCustomer>();
            string Baseurl = "http://localhost:5000/";

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("api/values");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var PersonResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    PersInfo = JsonConvert.DeserializeObject<List<OldCustomer>>(PersonResponse);

                }
                HttpContext.Session.SetObjectAsJson("_oldCustomer", PersInfo);
                return View("CustomerOverview", PersInfo);
            }

        }

    }
    }

CustomersAndOrdersCC/WebApplication/Views/Home/CreateNewCustomer.cshtml
@model CustomersAndOrdersCC.Data.Models.Customer

@{
    ViewData["Title"] = "CreateNewCustomer";
}

<h1>CreateNewCustomer</h1>

<h4>NewCustomer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("CreateCustomer", "CreateCustomer", FormMethod.Post))
        {
        <fieldset>
            <legend>Customer Info Input</legend>
            <p>
                Title :
                @Html.TextBoxFor(PersInfo => PersInfo.Title)
            </p>

            <p>
                First Name :
                @Html.TextBoxFor(PersInfo => PersInfo.FirstName)
            </p>

            <p>
                Middle Name :
                @Html.TextBoxFor(PersInfo => PersInfo.MiddleName)
            </p>

            <p>
                Last Name :
                @Html.TextBoxFor(PersInfo => PersInfo.LastName)
            </p>

            <p>
                Gender :
                @Html.TextBoxFor(PersInfo => PersInfo.Gender)
            </p>

            <p>
                EmailAddress :
                @Html.TextBoxFor(PersInfo => PersInfo.EmailAddress)
            </p>

            <p>
                Phone Number :
                @Html.TextBoxFor(PersInfo => PersInfo.HomePhoneNumber)
            </p>

            <p>
                Street :
                @Html.TextBoxFor(PersInfo => PersInfo.AddressLine1)
            </p>

            <p>
                HouseNr :
                @Html.TextBoxFor(PersInfo => PersInfo.AddressLine2)
            </p>

            <p>
                City :
                @Html.TextBoxFor(PersInfo => PersInfo.City)
            </p>

            <p>
                Postal Code :
                @Html.TextBoxFor(PersInfo => PersInfo.PostalCode)
            </p>

            <p>
                BusinessEntityID :
                @Html.TextBoxFor(PersInfo => PersInfo.BusinessEntityID)
            </p>



            <p>
                <br />
                <button type="submit">Create new Customer</button>
            </p>


        </fieldset>
        }
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomersAndOrdersCC/WebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CustomersAndOrdersCC/WebApplication/Views/Home/Landing.cshtml
@model WebApplication.Models.ModelClass

@{
    ViewData["Title"] = "Landing";
}

<h1>Calling Center App</h1>
<br />
<br />
<br />
<br />


@using (Html.BeginForm("Comparison", "Home", FormMethod.Post))
{

    <fieldset>
        <legend>Customer Info Input</legend>
        <p>
            First Name :
            @Html.TextBoxFor(model => model.MVCFirstName)
        </p>

        <p>
            Last Name :
            @Html.TextBoxFor(model => model.MVCLastName)
        </p>

        <p>
            <br />
            <button type="submit">Submit / Search Customer</button>
        </p>
        
        
    </fieldset>

}

@using (Html.BeginForm("CustomerOverview", "OcOverview", FormMethod.Post))
{
    <br />
    <button type="submit">View Old Customers</button>
}